# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Matcrawl < Formula
  desc "Local-first Matrix archive crawler"
  homepage "https://github.com/peetzweg/matcrawl"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peetzweg/matcrawl/releases/download/v0.2.0/matcrawl_0.2.0_darwin_amd64.tar.gz"
      sha256 "a3496ac05c05e213c81f4fa761397aca3266d1e3701d04af978032efccef15c6"

      define_method(:install) do
        bin.install "matcrawl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peetzweg/matcrawl/releases/download/v0.2.0/matcrawl_0.2.0_darwin_arm64.tar.gz"
      sha256 "6faaeb666bba1efef29e0076703f38831b951a816381d0c8580166f7cbc4aaf3"

      define_method(:install) do
        bin.install "matcrawl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peetzweg/matcrawl/releases/download/v0.2.0/matcrawl_0.2.0_linux_amd64.tar.gz"
      sha256 "6e2ab07bed81b67bef61fb780f2a539f1ea85a47ae852ff3039035311fc6f0a7"
      define_method(:install) do
        bin.install "matcrawl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peetzweg/matcrawl/releases/download/v0.2.0/matcrawl_0.2.0_linux_arm64.tar.gz"
      sha256 "8f578ca774b61ab5c14f1af36bfceaa4d1eb9d3e10297b6f671272a00921dafc"
      define_method(:install) do
        bin.install "matcrawl"
      end
    end
  end

  def caveats
    <<~EOS
      Run `matcrawl login` to authenticate against your Matrix homeserver,
      then `matcrawl keys import` with an Element room-keys export
      (Element → Settings → Security & Privacy → Export E2E room keys) to
      decrypt E2EE rooms.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/matcrawl version")
  end
end
