# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sigcrawl < Formula
  desc "Local-first Signal Desktop archive crawler"
  homepage "https://github.com/peetzweg/sigcrawl"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peetzweg/sigcrawl/releases/download/v0.2.1/sigcrawl_0.2.1_darwin_amd64.tar.gz"
      sha256 "3d5d299514be87039323bba7e5e2018537613b6558fbe6f9fb3d6f02a71145e6"

      define_method(:install) do
        bin.install "sigcrawl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peetzweg/sigcrawl/releases/download/v0.2.1/sigcrawl_0.2.1_darwin_arm64.tar.gz"
      sha256 "f63a877883bc64c00793a076191b3ffba9090a22cc4bb3ebeacb1fdcf227daf4"

      define_method(:install) do
        bin.install "sigcrawl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peetzweg/sigcrawl/releases/download/v0.2.1/sigcrawl_0.2.1_linux_amd64.tar.gz"
      sha256 "8db2b1d4f602c68283256437d057e3dc88a4bb8da117cd205869de7209ccd3f1"
      define_method(:install) do
        bin.install "sigcrawl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peetzweg/sigcrawl/releases/download/v0.2.1/sigcrawl_0.2.1_linux_arm64.tar.gz"
      sha256 "dfdf54c3f784ec1096f867d41ecdda17b52ee40d0f0122f97ecf429f86680359"
      define_method(:install) do
        bin.install "sigcrawl"
      end
    end
  end

  def caveats
    <<~EOS
      sigcrawl requires the `sigtop` binary for Signal Desktop SQLCipher
      decryption. Install it with:

        brew install --HEAD tbvdm/tap/sigtop
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sigcrawl version")
  end
end
