# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sigcrawl < Formula
  desc "Local-first Signal Desktop archive crawler"
  homepage "https://github.com/peetzweg/sigcrawl"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peetzweg/sigcrawl/releases/download/v0.2.0/sigcrawl_0.2.0_darwin_amd64.tar.gz"
      sha256 "5e084d5aaa27629a62c56d8d24f20a69cdb117a29b0b181feab1604a8bc2b454"

      define_method(:install) do
        bin.install "sigcrawl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peetzweg/sigcrawl/releases/download/v0.2.0/sigcrawl_0.2.0_darwin_arm64.tar.gz"
      sha256 "ff400feaa8a0077ca5ea754b3f41231cee8ad8e96b2153ea6f587bc83e18f7fa"

      define_method(:install) do
        bin.install "sigcrawl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peetzweg/sigcrawl/releases/download/v0.2.0/sigcrawl_0.2.0_linux_amd64.tar.gz"
      sha256 "1c98840751235f7bb26732db80538946a784907d2f4c6cd3b1d22ec954d6ce20"
      define_method(:install) do
        bin.install "sigcrawl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peetzweg/sigcrawl/releases/download/v0.2.0/sigcrawl_0.2.0_linux_arm64.tar.gz"
      sha256 "d7afed88344b06dab3722d5bbf35909b095c539eab59e3c5e0cf67e56a8bd060"
      define_method(:install) do
        bin.install "sigcrawl"
      end
    end
  end

  def caveats
    <<~EOS
      sigcrawl requires the `sigtop` binary for Signal Desktop SQLCipher
      decryption. Install it with:

        brew install --HEAD tbvdm/tap/sigtop
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sigcrawl version")
  end
end
